### PR TITLE
Fix root check in BootupService

### PR DESCRIPTION
**Pull request by chris54721**
The CPU/GPU frequency settings bootup restoration didn't work for me, so I played around with the bootup code a bit and noticed that the process got aborted if root WAS present.
This is probably how the root check should have been.

### CODE REVIEW

**Comment by pupaxxo** [comment]
:+1:

**Comment by Evisceration** [comment]
whoops, my bad!

thanks for keeping an eye on it :)

could you please rebase on the master branch again?
as the commit history seems to be a bit wonky.

**Comment by Chris54721** [comment]
Sorry for the commit mess, my bad

**Comment by Chris54721** [comment]
Looks like I made a giant mess. I'm going to make a new PR, sorry for this.

**Pull request closed without merging**
